name: PHP Vulnerability Test

on:
  push:
    branches:
      - main

jobs:
  php-lint:
    name: Linting

    runs-on: ubuntu-latest
    strategy:
      matrix:
        operating-system:
          - "ubuntu-22.04"
        php-version:
          - "8.2"

    steps:
      - name: Lint PHP files

        uses: overtrue/phplint@main
        with:
          path: src/
          options: --exclude=vendor